# Generated by Django 4.2.2 on 2023-06-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_alter_ticket_time_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
